### ISSUE TITLE
Update README with Team Partner Information

### ISSUE THREAD

**Issue by sooyoncho** [aetas-github-training/cho-test-repo#3]
Hi @CIS-PoonamSachdeva I need to add your name to my README file. Please provide me your full name so I can update this file. Thank you

**Comment by jgjucha** [comment]
jgjucha

**Comment by jgjucha** [comment]
jocelyn jucha

**Comment by CIS-PoonamSachdeva** [comment]
Hello here is my answer to your question

**Comment by CIS-PoonamSachdeva** [comment]
My full name is Poonam Sachdeva
